version: "3.6"
services:
    liked:
        image: likechain/likechain:sheungwan
        container_name: likechain_liked
        volumes:
            - ./.liked:/likechain/.liked
            - ./.likecli:/likechain/.likecli
        ports:
            - 26656:26656
            - 26657:26657
        restart: always
        command: ["liked", "--home", "/likechain/.liked", "--get-ip", "start", "--rpc.laddr", "tcp://0.0.0.0:26657", "--p2p.seeds", "__SEED_NODES__"]
networks:
    default:
        name: likechain
